meta_product_name: "CARETAKER"
meta_title: "CARETAKER - Helper for life!"
meta_description: "CARETAKER is the the most amazing app in the market right now!
                  It can help you take care of your loved ones! With this revolutionary app,
                  you will be able to remember of all your important events of your life
                  AND the ones of your loved ones! Incredibles, right?
                  You can be linked to your son/doughter or to your father/mother and supervise every event of their schedule!
                  What are you waiting for?
                  JOIN US!"
meta_image: 'caretaker_og.jpeg' # should exist in `app/assets/images/




